### ISSUE TITLE
Vega Dynamic Data example no longer animates

### ISSUE THREAD

**Issue by marcprux** [uwdata/vega#19]
The example at vega/examples/dynamic/index.html no longer animates the bars. It was working at e19b1f81c0381def61524fbd5e1d71d794e25101 and stopped working at b094e2565fbcb343f4d26f6d6a1f55bd19262f72, where the Safari console now reports:

``` console
[Error] TypeError: undefined is not an object (evaluating 'item.status = C.EXIT')
    joinChangeset (vega2.js, line 4942)
    evaluate (vega2.js, line 4840)
    propagate (vega2.js, line 1854)
    fire (vega2.js, line 6434)
    update (vega2.js, line 9480)
    timestep (index.html, line 118)
```

Note that even when it worked in e19b1f81c0381def61524fbd5e1d71d794e25101, it wasn't working as intended: the bottom bar's animation (when the "animation" checkbox is selected) shouldn't be a smooth transition because it doesn't set the mark's key fields.

**Comment by arvind** [comment]
Good catch, Marc. The js error is fixed with 024a5c2. The other issue is actually a change in Vega 2 -- we no longer index data tuples, because it would be expensive to reindex the entire data source every time tuples streamed in or out. Instead, every tuple is issued a constantly incrementing ID, and that ID is used by default for the data join on marks. There is no equivalent of the index join from before. I will update the example for final release to reflect this change. 

I'd be open to revisiting the decision on tuple indices if there's a compelling use for them. Feel free to reopen this issue, or a new one, in that case.
