### ISSUE TITLE
raise error if users refer to non-existing field

### ISSUE THREAD

**Issue by kanitw** [uwdata/vega#95]
Not sure if we do this in Vega 3 yet, but in Vega 2 we normally get native Javascript error. 
Probably more user friendly if we just have our own specific error.  

(Inspired from https://github.com/altair-viz/altair/issues/247 -- this might enable Altair to do this easier.)

**Comment by jakevdp** [comment]
One note on this: for Altair users (and I suspect users of other APIs) javascript errors printed to the console are basically useless. Many of our users wouldn't even know where to find the javascript console if you told them to look for it.

Much more useful would be for errors to actually be represented in the HTML output (say, a blank box containing red text indicating what went wrong), rather than the current behavior of displaying nothing and hoping the user knows where or what the console is.

**Comment by jheer** [comment]
I agree this would be useful. However, JavaScript allows lookup of non-existent fields, returning `undefined` in response. Vega can't do this error check at parse time, as in most cases we don't actually observe any data until runtime. Our internal field lookups could include existence checks, but (in the most straightforward implementation) at a cost of doing such a check **every time** a field is accessed. We would need to do some micro-benchmarking to assess potential performance hits here. 

There is also the issue that in some cases there may be "unbalanced" input data, with some fields defined on a subset of tuples but not others. Thus, we might further need special options on where and when to perform field checks. So I think this issue is a bit more complicated than it might seem at first.

It's possible that it is better to perform this check (and enforce a particular semantics) at the Vega-Lite or Altair level.

@jakevdp - I'll add a new issue regarding error output, which is a separate (and important) need!

**Comment by jheer** [comment]
Note that another solution might be to introduce a new Vega operator that does data quality assessment, such as checking that certain fields exist (and are appropriately typed?). That could be added by Vega-Lite in its compilation process, and would only have to run once.

**Comment by jheer** [comment]
Closing this issue now, as we migrate to the [vega/vega](https://github.com/vega/vega) repo. Feel free to re-open elsewhere with a more specific request -- for example, a quality-assessment operator in [vega-dataflow](https://github.com/vega/vega-dataflow).
